version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4001:4000"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "4002:4000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_backend
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "150MB"

networks:
  default:
    driver: bridge
    name: rinha_backend_network
