version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PHX_HOST=api01
      - SECRET_KEY_BASE="vnbnYw4N0WzDuQieEpv0tzaZCAGfNOzk/M+naf87PNX3yd2fM4COTizm3yVwwHh7"
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rinha_backend
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "4001:4001"
    depends_on:
      - api01
    environment:
      - PORT=4001
      - PHX_HOST=api02
      - SECRET_KEY_BASE="yd5mZeRqTh7KqzvBGTPIaN9yuIRoeQuqeeQCJKe8pqAXakf1p4zugNYfUGjp32C+"
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rinha_backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "20MB"


  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_backend
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "130MB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rinha_backend" ]
      interval: 3s
      timeout: 1s
      retries: 2

networks:
  default:
    driver: bridge
    name: rinha_backend_2024_q1
