version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4001:4000"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "4002:4000"
    depends_on:
      - api01

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_backend
    command: postgres -c max_connections=450 -c checkpoint_timeout=600 -c max_wal_size=4096
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "120MB"

networks:
  default:
    driver: bridge
    name: rinha_backend_2024_q1
